name: Sonar cloud setting

inputs:
  fetch-depth:
    description: 'sonar cloud fetch depth'
    required: false
    type: number
    default: 0
  token:
    description: 'sonar token'
    required: true
    type: string

runs:
  using: composite

  steps:
    - name: SonarCloud setting
      uses: SonarSource/sonarcloud-github-action@master
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
      env:
        SONAR_TOKEN: ${{ inputs.token }}
